### ISSUE TITLE
combining

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-melissa#2]
There will be a total of 12 files that will need to be combined on `id`. 
When we processed the 2018 file, 6 files were combined by ED, I had combined 12 outputs down to 6 files in excel. The layout and field sources used in 2018 can be found in Melissa_Geocoded_Layout_And_Field_Source.xlsx. 
The layout will remain the same, it is the field sources that will change.

**Comment by SPTKL** [comment]
Completed, need review @baolingz , check below file for build logic : 
[Melissa_Geocoded_Layout_And_Field_Source.xlsx](https://github.com/NYCPlanning/db-melissa/files/3636913/Melissa_Geocoded_Layout_And_Field_Source.xlsx)

**Comment by baolingz** [comment]
Reviewed. looks correct
